import streamlit as st
import pandas as pd
import altair as alt
import json
# Import Gemini API client (replace with the actual Gemini SDK or HTTP client)
import google.generativeai as genai

# Conversion rate: 1 USD = 35 THB
USD_TO_THB = 35

def df_to_json(df, name_metrics):
    """
    Convert a DataFrame to JSON format.

    Args:
        df (pd.DataFrame): The DataFrame to convert.

    Returns:
        str: JSON string representation of the DataFrame.
    """
    return df.to_json(f"{name_metrics}.json",indent=4, date_format='iso')

# Load data
def load_data():
    df = pd.read_csv("sample_data_fishery_thailand.csv", delimiter=",")
    df['date'] = pd.to_datetime(df['date'])  # Ensure 'date' is in datetime format
    df['province'] = df['province'].astype('category')
    df['type'] = df['type'].astype('category')
    
    # Convert values from 1000 USD to THB
    df['total_value_product'] = df['total_value_product'] * 1000 * USD_TO_THB
    df['unit_value'] = df['unit_value'] * 1000 * USD_TO_THB
    return df

df = load_data()

# Streamlit page settings
st.set_page_config(layout="wide")
st.title("Thailand Fishery Dashboard")
st.write("This dashboard provides insights into fishery production, economic trends, and geospatial distribution.")

# --- Auto-Generate Insights ---
st.markdown("### Insights and Summary")


# Configure the API key (or use service account if running on GCP)
genai.configure(api_key="AIzaSyBZGtJP6DCh9PReRA8-fiJNTLKyVXvxjlc")

# Load Gemini model
model = genai.GenerativeModel("gemini-2.0-flash")

def generate_insights(filtered_df):
    """
    Generate insights and key takeaways using Google's Gemini model.

    Args:
        filtered_df (pd.DataFrame): The DataFrame containing filtered fishery data.

    Returns:
        str: A textual insight generated by Gemini.
    """
    summary = f"""
    The dataset contains {len(filtered_df)} records after applying filters. 
    The total production is {filtered_df['total_quant_of_product'].sum():,.2f} tonnes, 
    with a total value of {filtered_df['total_value_product'].sum():,.2f} THB. 
    The average unit value is {filtered_df['unit_value'].mean():,.2f} THB.
    """

    prompt = f"Based on the following summary, generate insights and key takeaways:\n\n{summary}"

    response = model.generate_content(prompt)

    return response.text.strip()
  # Adjust based on Gemini's response format

# --- Header with Filters ---
with st.container():
    st.markdown("### Filters")
    col1, col2, col3, col4 = st.columns([1, 1, 1, 1])

    # Date Range Filter
    with col1:
        start_date = st.date_input("Start Date", df['date'].min())
        end_date = st.date_input("End Date", df['date'].max())

    # Province Filter (List-Box)
    with col2:
        province = st.selectbox("Select Province", options=["All"] + list(df['province'].unique()))
        if province != "All":
            df = df[df['province'] == province]

    # Type Filter (List-Box)
    with col3:
        type_filter = st.selectbox("Select Type", options=["All"] + list(df['type'].unique()))
        if type_filter != "All":
            df = df[df['type'] == type_filter]

    # Pieaces Filter (List-Box)
    with col4:
        pieace_filter = st.selectbox("Select Pieace", options=["All"] + list(df['pieaces'].unique()))
        if pieace_filter != "All":
            df = df[df['pieaces'] == pieace_filter]

# Apply Date Range Filter
filtered_df = df[(df['date'] >= pd.to_datetime(start_date)) & 
                 (df['date'] <= pd.to_datetime(end_date))]

# Display insights
if not filtered_df.empty:
    try:
        insights = generate_insights(filtered_df)
        st.write(insights)
    except Exception as e:
        st.write(f"Error generating insights: {e}")
else:
    st.write("No data available for the selected filters.")

# --- Layout: Geomap on the left, charts on the right ---
col1, col2 = st.columns([1, 3])

# LEFT: Geomap
with col1:
    st.markdown("### Geospatial View")
    st.components.v1.html(
        """
        <div style="min-height:400px" id="datawrapper-vis-FPm38"><script type="text/javascript" defer src="https://datawrapper.dwcdn.net/FPm38/embed.js" charset="utf-8" data-target="#datawrapper-vis-FPm38"></script><noscript><img src="https://datawrapper.dwcdn.net/FPm38/full.png" alt="" /></noscript></div>
        """,
        height=100000
    )

# RIGHT: Charts and Metrics
with col2:
    # Key Metrics
    st.markdown("### Key Metrics")
    total_production = filtered_df['total_quant_of_product'].sum()
    total_value = filtered_df['total_value_product'].sum()
    average_unit_value = filtered_df['unit_value'].mean()
    total_employment = filtered_df['total_emp'].sum()
    

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Production (Tonnes)", f"{total_production:,.2f}")
    col2.metric("Total Value (THB)", f"{total_value:,.2f}")
    col3.metric("Average Unit Value (THB)", f"{average_unit_value:,.2f}")
    col4.metric("Total Employment", f"{total_employment:,.0f}")

    # Production by Type (Pie Chart)
    st.markdown("### Production by Type")
    production_by_type = filtered_df.groupby('type')['total_quant_of_product'].sum().reset_index()
    pie_chart_production = alt.Chart(production_by_type).mark_arc().encode(
        theta=alt.Theta(field="total_quant_of_product", type="quantitative"),
        color=alt.Color(field="type", type="nominal"),
        tooltip=["type", alt.Tooltip("total_quant_of_product", format=",.2f", title="Production (Tonnes)")]
    ).properties(
        title="Total Production by Fishery Type"
    )
    st.altair_chart(pie_chart_production, use_container_width=True)

    # Value by Type (Pie Chart)
    st.markdown("### Value by Type")
    value_by_type = filtered_df.groupby('type')['total_value_product'].sum().reset_index()
    pie_chart_value = alt.Chart(value_by_type).mark_arc().encode(
        theta=alt.Theta(field="total_value_product", type="quantitative"),
        color=alt.Color(field="type", type="nominal"),
        tooltip=["type", alt.Tooltip("total_value_product", format=",.2f", title="Value (THB)")]
    ).properties(
        title="Total Value by Fishery Type"
    )
    st.altair_chart(pie_chart_value, use_container_width=True)

    # Production Over Time (Line Chart)
    st.markdown("### Production Over Time")
    production_over_time = filtered_df.groupby('date')['total_quant_of_product'].sum().reset_index()
    line_chart_production = alt.Chart(production_over_time).mark_line().encode(
        x=alt.X('date:T', title='Date'),
        y=alt.Y('total_quant_of_product:Q', title='Production (Tonnes)'),
        tooltip=['date:T', alt.Tooltip('total_quant_of_product', format=",.2f", title="Production (Tonnes)")]
    ).properties(
        title="Total Production Over Time"
    )
    st.altair_chart(line_chart_production, use_container_width=True)

    # Value Over Time (Line Chart)
    st.markdown("### Value Over Time")
    value_over_time = filtered_df.groupby('date')['total_value_product'].sum().reset_index()
    line_chart_value = alt.Chart(value_over_time).mark_line().encode(
        x=alt.X('date:T', title='Date'),
        y=alt.Y('total_value_product:Q', title='Value (THB)'),
        tooltip=['date:T', alt.Tooltip('total_value_product', format=",.2f", title="Value (THB)")]
    ).properties(
        title="Total Value Over Time"
    )
    st.altair_chart(line_chart_value, use_container_width=True)

    # Average Unit Value Over Time (Line Chart)
    st.markdown("### Average Unit Value Over Time")
    unit_value_over_time = filtered_df.groupby('date')['unit_value'].mean().reset_index()
    line_chart_unit_value = alt.Chart(unit_value_over_time).mark_line().encode(
        x=alt.X('date:T', title='Date'),
        y=alt.Y('unit_value:Q', title='Average Unit Value (THB)'),
        tooltip=['date:T', alt.Tooltip('unit_value', format=",.2f", title="Unit Value (THB)")]
    ).properties(
        title="Average Unit Value Over Time"
    )
    st.altair_chart(line_chart_unit_value, use_container_width=True)

    # Top Provinces by Production (Bar Chart)
    st.markdown("### Top Provinces by Production")
    top_production_provinces = filtered_df.groupby('province')['total_quant_of_product'].sum().sort_values(ascending=False).reset_index().head(5)
    bar_chart_production = alt.Chart(top_production_provinces).mark_bar().encode(
        x=alt.X('total_quant_of_product:Q', title='Production (Tonnes)'),
        y=alt.Y('province:N', sort='-x', title='Province'),
        tooltip=['province', alt.Tooltip('total_quant_of_product', format=",.2f", title="Production (Tonnes)")]
    ).properties(
        title="Top 5 Provinces by Production"
    )
    st.altair_chart(bar_chart_production, use_container_width=True)

    # Top Provinces by Value (Bar Chart)
    st.markdown("### Top Provinces by Value")
    top_value_provinces = filtered_df.groupby('province')['total_value_product'].sum().sort_values(ascending=False).reset_index().head(5)
    bar_chart_value = alt.Chart(top_value_provinces).mark_bar().encode(
        x=alt.X('total_value_product:Q', title='Value (THB)'),
        y=alt.Y('province:N', sort='-x', title='Province'),
        tooltip=['province', alt.Tooltip('total_value_product', format=",.2f", title="Value (THB)")]
    ).properties(
        title="Top 5 Provinces by Value"
    )
    st.altair_chart(bar_chart_value, use_container_width=True)

    # Monthly Comparison of Pieaces
    st.markdown("### Monthly Comparison of Pieaces")
    filtered_df['month'] = filtered_df['date'].dt.to_period('M')  # Extract month-year for grouping
    monthly_pieaces = filtered_df.groupby(['month', 'pieaces'])['total_quant_of_product'].sum().reset_index()
    monthly_pieaces['month'] = monthly_pieaces['month'].dt.to_timestamp()  # Convert period to timestamp for Altair

    # Create a line chart for monthly comparison
    monthly_pieaces_chart = alt.Chart(monthly_pieaces).mark_line(point=True).encode(
        x=alt.X('month:T', title='Month'),
        y=alt.Y('total_quant_of_product:Q', title='Total Production (Tonnes)'),
        color=alt.Color('pieaces:N', title='Pieaces'),
        tooltip=['month:T', 'pieaces:N', alt.Tooltip('total_quant_of_product:Q', format=",.2f", title="Production (Tonnes)")]
    ).properties(
        title="Monthly Comparison of Pieaces"
    )

    st.altair_chart(monthly_pieaces_chart, use_container_width=True)
    
    # Monthly Comparison of Province
    st.markdown("### Monthly Comparison of Province")
    filtered_df['month'] = filtered_df['date'].dt.to_period('M')  # Extract month-year for grouping
    monthly_pieaces = filtered_df.groupby(['month', 'province'])['total_quant_of_product'].sum().reset_index()
    monthly_pieaces['month'] = monthly_pieaces['month'].dt.to_timestamp()  # Convert period to timestamp for Altair

    # Create a line chart for monthly comparison
    monthly_pieaces_chart = alt.Chart(monthly_pieaces).mark_line(point=True).encode(
        x=alt.X('month:T', title='Month'),
        y=alt.Y('total_quant_of_product:Q', title='Total Production (Tonnes)'),
        color=alt.Color('province:N', title='Province'),
        tooltip=['month:T', 'province:N', alt.Tooltip('total_quant_of_product:Q', format=",.2f", title="Production (Tonnes)")]
    ).properties(
        title="Monthly Comparison of province"
    )

    st.altair_chart(monthly_pieaces_chart, use_container_width=True)

    # Export and Import Value Over Time (Line Chart)
    st.markdown("### Export and Import Value Over Time")
    st.write("This chart shows the trends of export and import values over time.")

    # Group data by date for export and import values
    export_import_over_time = filtered_df.groupby('date')[['export_value', 'import_value']].sum().reset_index()

    print(export_import_over_time)
    
    # Create a line chart for export and import values
    export_import_chart = alt.Chart(export_import_over_time).transform_fold(
        ['export_value', 'import_value'],  # Columns to fold
        as_=['Type', 'Value']  # Rename folded columns
    ).mark_line(point=True).encode(
        x=alt.X('date:T', title='Date'),
        y=alt.Y('Value:Q', title='Value (THB)'),
        color=alt.Color('Type:N', title='Type', scale=alt.Scale(scheme='set1')),
        tooltip=['date:T', 'Type:N', alt.Tooltip('Value:Q', format=",.2f", title="Value (THB)")]
    ).properties(
        title="Export and Import Value Over Time"
    )

    st.altair_chart(export_import_chart, use_container_width=True)

    # Net Trade Value Over Time (Line Chart)
    st.markdown("### Net Trade Value Over Time")
    st.write("This chart shows the net trade value (export - import) over time.")

    # Group data by date for net trade value
    net_trade_over_time = filtered_df.groupby('date')['net_trade_value'].sum().reset_index()

    print(net_trade_over_time)
    
    # Create a line chart for net trade value
    net_trade_chart = alt.Chart(net_trade_over_time).mark_line(point=True).encode(
        x=alt.X('date:T', title='Date'),
        y=alt.Y('net_trade_value:Q', title='Net Trade Value (THB)'),
        tooltip=['date:T', alt.Tooltip('net_trade_value:Q', format=",.2f", title="Net Trade Value (THB)")]
    ).properties(
        title="Net Trade Value Over Time"
    )

    st.altair_chart(net_trade_chart, use_container_width=True)

    # Top Provinces by Net Trade Value (Bar Chart)
    st.markdown("### Top Provinces by Net Trade Value")
    st.write("This bar chart shows the top provinces by net trade value.")

    # Group data by province for net trade value
    top_net_trade_provinces = filtered_df.groupby('province')['net_trade_value'].sum().sort_values(ascending=False).reset_index().head(5)

    # Create a bar chart for top provinces by net trade value
    top_net_trade_chart = alt.Chart(top_net_trade_provinces).mark_bar().encode(
        x=alt.X('net_trade_value:Q', title='Net Trade Value (THB)'),
        y=alt.Y('province:N', sort='-x', title='Province'),
        color=alt.Color('province:N', title='Province', scale=alt.Scale(scheme='set2')),
        tooltip=['province', alt.Tooltip('net_trade_value:Q', format=",.2f", title="Net Trade Value (THB)")]
    ).properties(
        title="Top 5 Provinces by Net Trade Value"
    )

    st.altair_chart(top_net_trade_chart, use_container_width=True)

# Function to export chart data to JSON
def export_chart_to_json(data, chart_name, file_path):
    """
    Export chart data to a JSON file in the specified format.

    Args:
        data (list): List of dictionaries containing chart data.
        chart_name (str): Name of the chart.
        file_path (str): Path to save the JSON file.
    """
    # Convert Timestamp objects to strings
    for record in data:
        for key, value in record.items():
            if isinstance(value, pd.Timestamp):
                record[key] = value.isoformat()  # Convert to ISO 8601 string

    json_data = {
        "value": data,
        "chart_name": chart_name
    }
    with open(file_path, "w") as json_file:
        json.dump(json_data, json_file, indent=4)
    print(f"Chart data exported to {file_path}")
    
def export_metrics_to_json(data, chart_name, file_path):
    """
    Export chart data to a JSON file in the specified format.

    Args:
        data (list): List of dictionaries containing chart data.
        chart_name (str): Name of the chart.
        file_path (str): Path to save the JSON file.
    """

    json_data = {
        "value": data,
        "chart_name": chart_name
    }
    with open(file_path, "w") as json_file:
        json.dump(json_data, json_file, indent=4)
    print(f"Chart data exported to {file_path}")

# # Example: Export Production by Type Chart
# production_by_type_data = production_by_type.to_dict(orient="records")
# export_chart_to_json(
#     data=production_by_type_data,
#     chart_name="production_by_type",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/production_by_type.json"
# )

# # Example: Export Value by Type Chart
# value_by_type_data = value_by_type.to_dict(orient="records")
# export_chart_to_json(
#     data=value_by_type_data,
#     chart_name="value_by_type",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/value_by_type.json"
# )

# # Example: Export Export and Import Value Over Time Chart
# export_import_data = export_import_over_time.to_dict(orient="records")
# export_chart_to_json(
#     data=export_import_data,
#     chart_name="export_import_over_time",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/export_import_over_time.json"
# )

# # Example: Export Net Trade Value Over Time Chart
# net_trade_data = net_trade_over_time.to_dict(orient="records")
# export_chart_to_json(
#     data=net_trade_data,
#     chart_name="net_trade_over_time",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/net_trade_over_time.json"
# )

# # Example: Export Top Provinces by Production Chart
# top_production_data = top_production_provinces.to_dict(orient="records")
# export_chart_to_json(
#     data=top_production_data,
#     chart_name="top_provinces_by_production",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/top_provinces_by_production.json"
# )

# # Example: Export Top Provinces by Net Trade Value Chart
# top_net_trade_data = top_net_trade_provinces.to_dict(orient="records")
# export_chart_to_json(
#     data=top_net_trade_data,
#     chart_name="top_provinces_by_net_trade_value",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/top_provinces_by_net_trade_value.json"
# )

# total_production = filtered_df['total_quant_of_product'].sum().to_dict(orient="records")
# export_metrics_to_json(
#     data=total_production,
#     chart_name="total_production",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/total_production.json"
# )

# total_value = filtered_df['total_value_product'].sum().to_dict(orient="records")
# export_metrics_to_json(
#     data=total_value,
#     chart_name="total_value",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/total_value.json"
# )

# average_unit_value = filtered_df['unit_value'].mean()
# export_metrics_to_json(
#     data=average_unit_value,
#     chart_name="average_unit_value",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/average_unit_value.json"
# )

# total_employment = filtered_df['total_emp'].sum().reset_index().to_dict(orient="records")
# export_metrics_to_json(
#     data=total_employment,
#     chart_name="total_employment",
#     file_path="/Users/trungtran/Documents/VNS/MD/data/metrics_data/total_employment.json"
# )